### ISSUE TITLE
[Feature request] Allow to zoom in/out on the preview

### ISSUE THREAD

**Issue by Kiiv** [sebthom/previewer-eclipse-plugin#2]
Hi,

thanks for the plugin ! Looking for something like this for a long time :)

Do you think it could be possible to add the possibility to zoom in a preview like mermaid ?
When diagrams are big it's pretty impossible to read them. Don't found any tools allowing that so it should be very great to have it ;)

Regards,
Clément.

**Comment by sebthom** [comment]
I added zooming now. please give it a try.

**Comment by Kiiv** [comment]
Hi !

It is working well for me !
Sometime there is some glitch on the text after zooming but it disappears as soon as the preview is refreshed :)

Thank you very much for your work.

**Comment by sebthom** [comment]
Nice, thanks for your feedback.
