### ISSUE TITLE
Mermaid preview fails when diagram contains '<' or '>'

### ISSUE THREAD

**Issue by Kiiv** [sebthom/previewer-eclipse-plugin#3]
Hi,

my diagram contain some '<' and '>' to identify return types.
The preview indicate that there is a syntax error.

Test with :
```
sequenceDiagram
    Client->>+Server: GET /my/api
    Server->>-Client : Map<String, String>
```

```mermaid
sequenceDiagram
    Client->>+Server: GET /my/api
    Server->>-Client : Map<String, String>
```

**Comment by sebthom** [comment]
Works fine for me:
![image](https://github.com/sebthom/previewer-eclipse-plugin/assets/426959/1a52a136-b9b6-4ac7-ae93-2a465caffc81)

**Comment by Kiiv** [comment]
Damn, can't reproduce ether... Don't know how I get that, maybe a refresh does not append after an other error. Sorry for the inconvenience.

Anyway, there still something weird ;)
```
Map<String, string="></string,>
```

The character probably broke the html behind.
